[book]
authors = ["Adeoye Adefemi"]
language = "en"
multilingual = false
src = "src"
description = "Backend development guide for non-techical people"
title = "Backend Roadmap for Humans"
github = "https://github.com/opeolluwa/backend-for-humans"

[build]
extra-watch-dirs = ["./exercises"]

[preprocessor.alerts]

[preprocessor.repl]
src = "https://mr-addict.github.io/mdbook-repl/embed/"
javascript.enable = true
javascript.loading = "lazy"
python.enable = true
python.loading = "lazy"

[preprocessor.embed]

[preprocessor.quiz]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
git-repository-url = "https://github.com/opeolluwa/backend-for-humans"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/opeolluwa/backend-for-humans/edit/master/{path}"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]