[book]
authors = ["Adeoye Adefemi"]
language = "en"
multilingual = false
src = "src"
description = "Backend development guide for non-techical people"
title = "Backend Roadmap for Humans"
github = "https://github.com/opeolluwa/backend-for-humans"

[build]
extra-watch-dirs = ["./exercises"]

[preprocessor.alerts]

[preprocessor.repl]
src = "https://mr-addict.github.io/mdbook-repl/embed/"
javascript.enable = true
javascript.loading = "lazy"
python.enable = true
python.loading = "lazy"

[preprocessor.embed]

[preprocessor.quiz]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
git-repository-url = "https://github.com/opeolluwa/backend-for-humans"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/opeolluwa/backend-for-humans/edit/master/{path}"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
additional-css =["last-changed.css"]

[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]



# [preprocessor.codeblocks]
# renderers = ["html"]
# cpp = { color = "#FFFF99", link = "https://wiki.redmodding.org/red4ext" }
# redscript = { color = "tomato", link = "https://wiki.redmodding.org/redscript" }
# rust = { color = "#ac4313", link = "https://github.com/jac3km4/red4ext-rs" }
# lua = { link = "https://wiki.redmodding.org/cyber-engine-tweaks" }
# swift = { label = "Swift code snippet", color = "skyblue" }
# javascript = {label ="JavaScript coe snippet", color ="#fdca00"}