[[questions]]
type = "ShortAnswer"
prompt.prompt = "______ is a kind of program used to welcome new programmers into the community"
context = ""
answer.answer = "hello world"
id = "c42a2266-2f3b-4aa3-88dc-69b2bb81b82a"


[[questions]]
type = "ShortAnswer"
prompt.prompt = "______ created JavaScript"
context = ""
id = "71d17c7e-a2d6-4db3-92dc-f40ee90da5b4"
answer.answer = "Brendan Eich"


[[questions]]
type = "ShortAnswer"
prompt.prompt = "______ created NodeJs"
context = ""
id = "23095655-3a7e-42b9-ba08-fe8e71d4d5aa"
answer.answer = "Ryan Dahl"


[[questions]]
type = "MultipleChoice"
prompt.prompt = "______ created is not a valid JavaScript extension"
prompt.distractors = [
    "Application software",
    "Utility software",
    "Programming software",
]
answer.answer = "System software"
id = "f30327fd-23d3-409c-93c9-65e3df40bf81"
